<?php
require_once 'config.php';

if (!isLoggedIn()) {
    redirect('login.php');
}

// Get the start_date and end_date from the query parameters
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : null;
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : null;

// Query the database based on the date range
if ($start_date && $end_date) {
    // Fetch drugs within the date range for the current organization
    $drug_sql = "SELECT * FROM drug WHERE organization_id = ? AND reception_date BETWEEN ? AND ?";
    $drug_stmt = $conn->prepare($drug_sql);
    $drug_stmt->bind_param("iss", $_SESSION['organization_id'], $start_date, $end_date);
    $drug_stmt->execute();
    $drug_result = $drug_stmt->get_result();
    $drugs = $drug_result->fetch_all(MYSQLI_ASSOC);

    $expired_sql = "SELECT * FROM expired_drug WHERE organization_id = ? AND reception_date BETWEEN ? AND ?";
    $expired_stmt = $conn->prepare($expired_sql);
    $expired_stmt->bind_param("iss", $_SESSION['organization_id'], $start_date, $end_date);
    $expired_stmt->execute();
    $expired_result = $expired_stmt->get_result();
    $expired_drugs = $expired_result->fetch_all(MYSQLI_ASSOC);
} else {
    // If no date range is provided, fetch all drugs and expired drugs for the current organization
    $drug_sql = "SELECT * FROM drug WHERE organization_id = ?";
    $drug_stmt = $conn->prepare($drug_sql);
    $drug_stmt->bind_param("i", $_SESSION['organization_id']);
    $drug_stmt->execute();
    $drug_result = $drug_stmt->get_result();
    $drugs = $drug_result->fetch_all(MYSQLI_ASSOC);

    $expired_sql = "SELECT * FROM expired_drug WHERE organization_id = ?";
    $expired_stmt = $conn->prepare($expired_sql);
    $expired_stmt->bind_param("i", $_SESSION['organization_id']);
    $expired_stmt->execute();
    $expired_result = $expired_stmt->get_result();
    $expired_drugs = $expired_result->fetch_all(MYSQLI_ASSOC);
}

// Combine the drugs and expired_drugs lists
$all_drugs = array_merge($drugs, $expired_drugs);

// Calculate totals
$total_stock = array_sum(array_column($all_drugs, 'total_stock'));
$total_used = array_sum(array_column($all_drugs, 'used'));
$total_remaining = array_sum(array_column($all_drugs, 'remaining'));

include 'header.php';
?>

<div class="container mt-4">
    <h2 class="text-center">Summary Report</h2>

    <!-- Print Button -->
    <div class="d-flex justify-content-start mb-3 no-print">
        <button class="btn btn-success" onclick="window.print()">Print Report</button>
    </div>

    <!-- Report Details -->
    <div class="card">
        <div class="card-header">Report Details</div>
        <div class="card-body">
            <p><strong>Report Date:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
            <p><strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['username']); ?></p>
        </div>
    </div>

    <!-- Stock Summary Card -->
    <div class="card mt-4">
        <div class="card-header">Stock Summary</div>
        <div class="card-body">
            <p><strong>Total Stock:</strong> <?php echo $total_stock; ?></p>
            <p><strong>Total Used:</strong> <?php echo $total_used; ?></p>
            <p><strong>Total Remaining:</strong> <?php echo $total_remaining; ?></p>
        </div>
    </div>

    <!-- Detailed Stock Report Card -->
    <div class="card mt-4">
        <div class="card-header">Detailed Stock Report</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead class="table-dark">
                        <tr>
                            <th>Name</th>
                            <th>Reception Date</th>
                            <th>Date of first use</th>
                            <th>From whom Received</th>
                            <th>Quantity Received</th>
                            <th>Quantity Issued</th>
                            <th>Loss/Adjust</th>
                            <th>Quantity in Stock</th>
                            <th>Company Name</th>
                            <th>Expiry Date</th>
                            <th>Date Out of Service</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($all_drugs as $drug): ?>
                            <tr>
                                <td><?php echo htmlspecialchars($drug['name']); ?></td>
                                <td><?php echo $drug['reception_date']; ?></td>
                                <td><?php echo $drug['first_used_date'] ?: 'N/A'; ?></td>
                                <td><?php echo htmlspecialchars($drug['received_from']); ?></td>
                                <td><?php echo $drug['total_stock']; ?></td>
                                <td><?php echo $drug['used']; ?></td>
                                <td><?php echo $drug['losses_adjustment']; ?></td>
                                <td><?php echo $drug['remaining']; ?></td>
                                <td><?php echo htmlspecialchars($drug['company_name']); ?></td>
                                <td><?php echo $drug['expiry_date']; ?></td>
                                <td><?php echo $drug['date_finished'] ?: 'N/A'; ?></td>
                                <td>
                                    <?php if (isset($drug['is_maintained']) && $drug['is_maintained']): ?>
                                        <span class="badge bg-success">Valid</span>
                                    <?php else: ?>
                                        <span class="badge bg-danger">Expired</span>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>